---
format: gfm
default-image-extension: ""
bibliography: references.bib
---

# Biostatistics for Fluid and Imaging Biomarkers of Neurodegeneration in R

This repository hosts the course materials for the biostatistics module of the [Biomarkers for Neurodegenerative Disorders](https://biomarker-course.org) course Barcelona, Spain, June 1-5, 2026.

Statistical and visualization techniques will be demonstrated using [R](https://www.r-project.org/) applied to data from the from the **Anti-Amyloid Treatment in Asymptomatic Alzheimer’s (A4) trial** and the **Longitudinal Evaluation of Amyloid Risk and Neurodegeneration (LEARN)** study and `A4LEARN` `R` package [@A4LEARN].

If you would like to follow along with the course materials, please obtain and install:

1. [`R`](https://cran.r-project.org) and [RStudio](https://posit.co/download/rstudio-desktop)
2. The [`A4LEARN`](https://www.a4studydata.org/) package and data.
3. Other packages (see below)
4. The course slides and code examples (`.R`, `.qmd` files) from this repository.

# `A4LEARN`

`A4LEARN` is an R study package [@donohue2026alzverse] that bundles

-   data,
-   documentation, and
-   reproducible analysis examples.

To obtain and install `A4LEARN`:

-   Register at <https://www.a4studydata.org/> or <https://www.synapse.org/a4_learn_datasharing/>
-   Download `A4LEARN_1.1.20250808.tar.gz` from the preferred data sharing platform
-   In R, run `install.packages("path/to/A4LEARN_1.1.20250808.tar.gz", repos = NULL, type = "source")`

# Other `R` packages

```{r, echo = TRUE, eval = FALSE}
# Installs packages needed for the A4LEARN / biomarker statistics workshop.

cran_packages <- c(
  "tidyverse",
  "arsenal",
  "kableExtra",
  "nlme",
  "emmeans",
  "clubSandwich",
  "broom",
  "mixtools",
  "patchwork",
  "reactable",
  "mmrm",
  "mice",
  "BiocManager" # for sva::ComBat batch correction
)

for(pkg in cran_packages){
  # check if package is installed, and if not, install it from CRAN
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org")
  }
}

# for sva::ComBat batch correction
if (!requireNamespace("sva", quietly = TRUE)){
  BiocManager::install("sva")
}
```

## The 90 minute course plan

-   **0 to 10 min**: orientation and A4LEARN setup
-   **10 to 30 min**: technical artifacts, baseline biomarker summaries, visualization
-   **30 to 50 min**: imaging biomarker interpretation and standardization using amyloid PET (CL)
-   **50 to 80 min**: longitudinal PACC trajectories and mixed effects models
-   **80 to 90 min**: synthesis and decision framework

# References

::: {#refs}
:::

